version: '3.8'

secrets:
  oanda_token:
    external: true
  oanda_account:
    external: true

services:
  forex-trader:
    image: cnewell826/forex-trader-worker:v3
    command: ["python", "app.py"]
    secrets:
      - oanda_token
      - oanda_account
      - telegram_bot_token
      - telegram_chat_id
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
